from __future__ import annotations

import json
import re
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from statistics import mean
from typing import Any

from sqlalchemy.orm import Session

from app.core.settings import Settings
from app.services.live_candidate_scoring import (
    build_live_candidate_opportunities,
    build_social_political_overlay,
)


@dataclass(frozen=True, slots=True)
class OpportunitySeed:
    site_name: str
    corridor_name: str
    metro: str
    city: str
    county: str
    region: str
    university_anchor: str
    acreage_band: str
    distance_to_city_miles: int
    distance_to_university_miles: int
    viability_score: int
    power_score: int
    fiber_score: int
    water_score: int
    talent_score: int
    readiness_stage: str
    power_profile: str
    fiber_profile: str
    water_profile: str
    lat: float
    lon: float


_OPPORTUNITY_SEEDS: tuple[OpportunitySeed, ...] = (
    OpportunitySeed(
        site_name="Plano North Utility Belt",
        corridor_name="DFW North Compute Crescent",
        metro="Dallas-Fort Worth",
        city="Plano",
        county="Collin County",
        region="North Texas",
        university_anchor="University of Texas at Dallas",
        acreage_band="140-220 acres",
        distance_to_city_miles=14,
        distance_to_university_miles=8,
        viability_score=96,
        power_score=95,
        fiber_score=97,
        water_score=82,
        talent_score=96,
        readiness_stage="Priority now",
        power_profile="high-voltage utility headroom",
        fiber_profile="carrier-dense metro adjacency",
        water_profile="municipal and reclaimed water optionality",
        lat=33.0500,
        lon=-96.7500,
    ),
    OpportunitySeed(
        site_name="Frisco Research Exchange",
        corridor_name="DFW North Compute Crescent",
        metro="Dallas-Fort Worth",
        city="Frisco",
        county="Collin County",
        region="North Texas",
        university_anchor="University of Texas at Dallas",
        acreage_band="180-260 acres",
        distance_to_city_miles=19,
        distance_to_university_miles=15,
        viability_score=94,
        power_score=93,
        fiber_score=96,
        water_score=80,
        talent_score=94,
        readiness_stage="Priority now",
        power_profile="redundant substation access",
        fiber_profile="multiple long-haul carrier paths",
        water_profile="stable municipal supply planning",
        lat=33.1500,
        lon=-96.8200,
    ),
    OpportunitySeed(
        site_name="Richardson Carrier Grid",
        corridor_name="DFW North Compute Crescent",
        metro="Dallas-Fort Worth",
        city="Richardson",
        county="Dallas County",
        region="North Texas",
        university_anchor="University of Texas at Dallas",
        acreage_band="95-155 acres",
        distance_to_city_miles=12,
        distance_to_university_miles=3,
        viability_score=93,
        power_score=91,
        fiber_score=98,
        water_score=79,
        talent_score=96,
        readiness_stage="Priority now",
        power_profile="proven utility redundancy",
        fiber_profile="dense carrier hotel access",
        water_profile="low-friction municipal service extensions",
        lat=32.9800,
        lon=-96.7200,
    ),
    OpportunitySeed(
        site_name="McKinney Expansion Ridge",
        corridor_name="DFW North Compute Crescent",
        metro="Dallas-Fort Worth",
        city="McKinney",
        county="Collin County",
        region="North Texas",
        university_anchor="University of Texas at Dallas",
        acreage_band="220-320 acres",
        distance_to_city_miles=27,
        distance_to_university_miles=18,
        viability_score=91,
        power_score=92,
        fiber_score=89,
        water_score=81,
        talent_score=90,
        readiness_stage="Near-term build",
        power_profile="scalable transmission tie-ins",
        fiber_profile="northbound metro fiber routes",
        water_profile="expansion-friendly municipal capacity",
        lat=33.2000,
        lon=-96.6700,
    ),
    OpportunitySeed(
        site_name="Lancaster South Interconnect",
        corridor_name="DFW North Compute Crescent",
        metro="Dallas-Fort Worth",
        city="Lancaster",
        county="Dallas County",
        region="North Texas",
        university_anchor="Southern Methodist University",
        acreage_band="200-310 acres",
        distance_to_city_miles=18,
        distance_to_university_miles=25,
        viability_score=89,
        power_score=93,
        fiber_score=86,
        water_score=83,
        talent_score=87,
        readiness_stage="Near-term build",
        power_profile="strong south Dallas utility corridors",
        fiber_profile="intermodal fiber convergence",
        water_profile="industrial-scale municipal planning",
        lat=32.5900,
        lon=-96.7600,
    ),
    OpportunitySeed(
        site_name="Alliance North Logistics Powerfield",
        corridor_name="Fort Worth Alliance Talent Loop",
        metro="Dallas-Fort Worth",
        city="Fort Worth",
        county="Tarrant County",
        region="North Texas",
        university_anchor="University of North Texas",
        acreage_band="210-300 acres",
        distance_to_city_miles=17,
        distance_to_university_miles=26,
        viability_score=94,
        power_score=96,
        fiber_score=92,
        water_score=78,
        talent_score=90,
        readiness_stage="Priority now",
        power_profile="utility-scale interconnect capacity",
        fiber_profile="alliance logistics fiber density",
        water_profile="industrial reuse partnerships nearby",
        lat=32.9800,
        lon=-97.3200,
    ),
    OpportunitySeed(
        site_name="Denton Research Utility Plateau",
        corridor_name="Fort Worth Alliance Talent Loop",
        metro="Dallas-Fort Worth",
        city="Denton",
        county="Denton County",
        region="North Texas",
        university_anchor="University of North Texas",
        acreage_band="160-240 acres",
        distance_to_city_miles=14,
        distance_to_university_miles=6,
        viability_score=92,
        power_score=90,
        fiber_score=89,
        water_score=81,
        talent_score=95,
        readiness_stage="Priority now",
        power_profile="balanced grid headroom",
        fiber_profile="I-35 carrier adjacency",
        water_profile="reliable municipal expansion capacity",
        lat=33.2200,
        lon=-97.1300,
    ),
    OpportunitySeed(
        site_name="Arlington Innovation Relay",
        corridor_name="Fort Worth Alliance Talent Loop",
        metro="Dallas-Fort Worth",
        city="Arlington",
        county="Tarrant County",
        region="North Texas",
        university_anchor="University of Texas at Arlington",
        acreage_band="110-170 acres",
        distance_to_city_miles=15,
        distance_to_university_miles=4,
        viability_score=90,
        power_score=88,
        fiber_score=93,
        water_score=79,
        talent_score=94,
        readiness_stage="Near-term build",
        power_profile="urban utility redundancy",
        fiber_profile="dense enterprise network routes",
        water_profile="mature city service infrastructure",
        lat=32.7300,
        lon=-97.1000,
    ),
    OpportunitySeed(
        site_name="Roanoke Fiber Junction",
        corridor_name="Fort Worth Alliance Talent Loop",
        metro="Dallas-Fort Worth",
        city="Roanoke",
        county="Denton County",
        region="North Texas",
        university_anchor="University of North Texas",
        acreage_band="130-210 acres",
        distance_to_city_miles=18,
        distance_to_university_miles=20,
        viability_score=88,
        power_score=89,
        fiber_score=91,
        water_score=77,
        talent_score=88,
        readiness_stage="Near-term build",
        power_profile="flexible substation adjacency",
        fiber_profile="northwest DFW backbone access",
        water_profile="municipal service with room to scale",
        lat=33.0000,
        lon=-97.2300,
    ),
    OpportunitySeed(
        site_name="Weatherford West Reserve",
        corridor_name="Fort Worth Alliance Talent Loop",
        metro="Dallas-Fort Worth",
        city="Weatherford",
        county="Parker County",
        region="North Texas",
        university_anchor="Texas Christian University",
        acreage_band="260-380 acres",
        distance_to_city_miles=33,
        distance_to_university_miles=34,
        viability_score=84,
        power_score=87,
        fiber_score=80,
        water_score=81,
        talent_score=82,
        readiness_stage="Strategic reserve",
        power_profile="large-format utility expansion room",
        fiber_profile="westbound interstate fiber access",
        water_profile="long-horizon municipal planning",
        lat=32.7600,
        lon=-97.8000,
    ),
    OpportunitySeed(
        site_name="Round Rock Semiconductor Loop",
        corridor_name="Austin North Innovation Arc",
        metro="Austin",
        city="Round Rock",
        county="Williamson County",
        region="Central Texas",
        university_anchor="University of Texas at Austin",
        acreage_band="120-190 acres",
        distance_to_city_miles=17,
        distance_to_university_miles=21,
        viability_score=95,
        power_score=90,
        fiber_score=95,
        water_score=78,
        talent_score=97,
        readiness_stage="Priority now",
        power_profile="proven semiconductor utility depth",
        fiber_profile="rich metro fiber ring access",
        water_profile="industrial service planning with reuse options",
        lat=30.5300,
        lon=-97.6800,
    ),
    OpportunitySeed(
        site_name="Georgetown Power Availability Shelf",
        corridor_name="Austin North Innovation Arc",
        metro="Austin",
        city="Georgetown",
        county="Williamson County",
        region="Central Texas",
        university_anchor="University of Texas at Austin",
        acreage_band="210-320 acres",
        distance_to_city_miles=28,
        distance_to_university_miles=29,
        viability_score=93,
        power_score=94,
        fiber_score=88,
        water_score=80,
        talent_score=91,
        readiness_stage="Priority now",
        power_profile="high-capacity transmission access",
        fiber_profile="north Austin corridor adjacency",
        water_profile="municipal growth-oriented water planning",
        lat=30.6400,
        lon=-97.6700,
    ),
    OpportunitySeed(
        site_name="Pflugerville Edge Fabric Yard",
        corridor_name="Austin North Innovation Arc",
        metro="Austin",
        city="Pflugerville",
        county="Travis County",
        region="Central Texas",
        university_anchor="University of Texas at Austin",
        acreage_band="115-175 acres",
        distance_to_city_miles=18,
        distance_to_university_miles=19,
        viability_score=92,
        power_score=89,
        fiber_score=94,
        water_score=77,
        talent_score=95,
        readiness_stage="Priority now",
        power_profile="flexible utility redundancy",
        fiber_profile="strong hyperscale fiber adjacency",
        water_profile="urban water service continuity",
        lat=30.4500,
        lon=-97.6200,
    ),
    OpportunitySeed(
        site_name="Hutto Expansion Corridor",
        corridor_name="Austin North Innovation Arc",
        metro="Austin",
        city="Hutto",
        county="Williamson County",
        region="Central Texas",
        university_anchor="University of Texas at Austin",
        acreage_band="190-280 acres",
        distance_to_city_miles=25,
        distance_to_university_miles=29,
        viability_score=89,
        power_score=91,
        fiber_score=85,
        water_score=79,
        talent_score=88,
        readiness_stage="Near-term build",
        power_profile="expandable utility corridor frontage",
        fiber_profile="east-northeast carrier pathways",
        water_profile="municipal reserve capacity",
        lat=30.5400,
        lon=-97.5500,
    ),
    OpportunitySeed(
        site_name="San Marcos Compute Bridge",
        corridor_name="Austin North Innovation Arc",
        metro="Austin-San Antonio Corridor",
        city="San Marcos",
        county="Hays County",
        region="Central Texas",
        university_anchor="Texas State University",
        acreage_band="170-260 acres",
        distance_to_city_miles=30,
        distance_to_university_miles=3,
        viability_score=88,
        power_score=87,
        fiber_score=88,
        water_score=80,
        talent_score=92,
        readiness_stage="Near-term build",
        power_profile="corridor utility optionality",
        fiber_profile="I-35 backbone connectivity",
        water_profile="balanced municipal and reclaimed options",
        lat=29.8800,
        lon=-97.9400,
    ),
    OpportunitySeed(
        site_name="Schertz Grid Access Campus",
        corridor_name="San Antonio Research Triangle",
        metro="San Antonio",
        city="Schertz",
        county="Guadalupe County",
        region="South Texas",
        university_anchor="University of Texas at San Antonio",
        acreage_band="180-260 acres",
        distance_to_city_miles=22,
        distance_to_university_miles=24,
        viability_score=92,
        power_score=92,
        fiber_score=88,
        water_score=83,
        talent_score=90,
        readiness_stage="Priority now",
        power_profile="robust utility access east of San Antonio",
        fiber_profile="corridor-grade network redundancy",
        water_profile="municipal resilience planning",
        lat=29.5500,
        lon=-98.2700,
    ),
    OpportunitySeed(
        site_name="New Braunfels I-35 Reserve",
        corridor_name="San Antonio Research Triangle",
        metro="San Antonio",
        city="New Braunfels",
        county="Comal County",
        region="South Texas",
        university_anchor="Texas State University",
        acreage_band="220-340 acres",
        distance_to_city_miles=29,
        distance_to_university_miles=20,
        viability_score=91,
        power_score=90,
        fiber_score=87,
        water_score=84,
        talent_score=89,
        readiness_stage="Priority now",
        power_profile="scalable power delivery options",
        fiber_profile="I-35 midpoint backbone access",
        water_profile="favorable municipal growth planning",
        lat=29.7000,
        lon=-98.1200,
    ),
    OpportunitySeed(
        site_name="Cibolo Mission Fiber Yard",
        corridor_name="San Antonio Research Triangle",
        metro="San Antonio",
        city="Cibolo",
        county="Guadalupe County",
        region="South Texas",
        university_anchor="University of Texas at San Antonio",
        acreage_band="150-220 acres",
        distance_to_city_miles=24,
        distance_to_university_miles=27,
        viability_score=88,
        power_score=88,
        fiber_score=89,
        water_score=81,
        talent_score=87,
        readiness_stage="Near-term build",
        power_profile="steady utility expansion options",
        fiber_profile="metro and interstate fiber proximity",
        water_profile="municipal service continuity",
        lat=29.5600,
        lon=-98.2300,
    ),
    OpportunitySeed(
        site_name="Seguin Industrial Water Shelf",
        corridor_name="San Antonio Research Triangle",
        metro="San Antonio",
        city="Seguin",
        county="Guadalupe County",
        region="South Texas",
        university_anchor="Texas State University",
        acreage_band="240-360 acres",
        distance_to_city_miles=34,
        distance_to_university_miles=20,
        viability_score=85,
        power_score=86,
        fiber_score=82,
        water_score=86,
        talent_score=84,
        readiness_stage="Strategic reserve",
        power_profile="large-site utility staging room",
        fiber_profile="regional corridor backhaul access",
        water_profile="strong industrial water planning",
        lat=29.5700,
        lon=-97.9600,
    ),
    OpportunitySeed(
        site_name="Katy West Power Exchange",
        corridor_name="Houston Capacity Ring",
        metro="Houston",
        city="Katy",
        county="Harris County",
        region="Gulf Coast",
        university_anchor="University of Houston",
        acreage_band="200-320 acres",
        distance_to_city_miles=29,
        distance_to_university_miles=33,
        viability_score=95,
        power_score=95,
        fiber_score=92,
        water_score=84,
        talent_score=90,
        readiness_stage="Priority now",
        power_profile="massive west Houston utility depth",
        fiber_profile="carrier routes along major logistics corridors",
        water_profile="industrial-scale municipal water planning",
        lat=29.7900,
        lon=-95.8300,
    ),
    OpportunitySeed(
        site_name="Cypress Carrier Density Park",
        corridor_name="Houston Capacity Ring",
        metro="Houston",
        city="Cypress",
        county="Harris County",
        region="Gulf Coast",
        university_anchor="Rice University",
        acreage_band="160-240 acres",
        distance_to_city_miles=27,
        distance_to_university_miles=31,
        viability_score=93,
        power_score=92,
        fiber_score=93,
        water_score=81,
        talent_score=90,
        readiness_stage="Priority now",
        power_profile="resilient northwest Houston substations",
        fiber_profile="dense carrier concentration",
        water_profile="stable municipal service envelope",
        lat=29.9700,
        lon=-95.7000,
    ),
    OpportunitySeed(
        site_name="Sugar Land Research Utility Hub",
        corridor_name="Houston Capacity Ring",
        metro="Houston",
        city="Sugar Land",
        county="Fort Bend County",
        region="Gulf Coast",
        university_anchor="University of Houston",
        acreage_band="140-220 acres",
        distance_to_city_miles=22,
        distance_to_university_miles=24,
        viability_score=92,
        power_score=90,
        fiber_score=91,
        water_score=83,
        talent_score=89,
        readiness_stage="Priority now",
        power_profile="well-developed utility infrastructure",
        fiber_profile="enterprise and long-haul path overlap",
        water_profile="municipal and reuse flexibility",
        lat=29.6200,
        lon=-95.6300,
    ),
    OpportunitySeed(
        site_name="The Woodlands Resilience Campus",
        corridor_name="Houston Capacity Ring",
        metro="Houston",
        city="The Woodlands",
        county="Montgomery County",
        region="Gulf Coast",
        university_anchor="Rice University",
        acreage_band="180-280 acres",
        distance_to_city_miles=36,
        distance_to_university_miles=43,
        viability_score=90,
        power_score=91,
        fiber_score=88,
        water_score=86,
        talent_score=85,
        readiness_stage="Near-term build",
        power_profile="north Houston utility resilience",
        fiber_profile="diverse carrier routing north of Houston",
        water_profile="robust suburban water systems",
        lat=30.1600,
        lon=-95.4600,
    ),
    OpportunitySeed(
        site_name="Pearland South Loop Reserve",
        corridor_name="Houston Capacity Ring",
        metro="Houston",
        city="Pearland",
        county="Brazoria County",
        region="Gulf Coast",
        university_anchor="Rice University",
        acreage_band="180-290 acres",
        distance_to_city_miles=22,
        distance_to_university_miles=24,
        viability_score=88,
        power_score=88,
        fiber_score=86,
        water_score=84,
        talent_score=87,
        readiness_stage="Near-term build",
        power_profile="south loop utility expandability",
        fiber_profile="regional backhaul proximity",
        water_profile="reliable municipal growth capacity",
        lat=29.5600,
        lon=-95.2900,
    ),
    OpportunitySeed(
        site_name="Bryan Innovation Utility Plain",
        corridor_name="College Station Research Energy Axis",
        metro="College Station",
        city="Bryan",
        county="Brazos County",
        region="Central Texas",
        university_anchor="Texas A&M University",
        acreage_band="170-250 acres",
        distance_to_city_miles=8,
        distance_to_university_miles=6,
        viability_score=92,
        power_score=90,
        fiber_score=85,
        water_score=84,
        talent_score=95,
        readiness_stage="Priority now",
        power_profile="research-oriented utility stability",
        fiber_profile="regional backbone access",
        water_profile="strong municipal planning support",
        lat=30.6700,
        lon=-96.3700,
    ),
    OpportunitySeed(
        site_name="College Station Talent Buffer",
        corridor_name="College Station Research Energy Axis",
        metro="College Station",
        city="College Station",
        county="Brazos County",
        region="Central Texas",
        university_anchor="Texas A&M University",
        acreage_band="110-180 acres",
        distance_to_city_miles=6,
        distance_to_university_miles=3,
        viability_score=91,
        power_score=88,
        fiber_score=86,
        water_score=82,
        talent_score=97,
        readiness_stage="Priority now",
        power_profile="dependable utility redundancy",
        fiber_profile="research park network adjacency",
        water_profile="campus-proximate municipal service",
        lat=30.6000,
        lon=-96.3400,
    ),
    OpportunitySeed(
        site_name="Navasota Strategic Reserve",
        corridor_name="College Station Research Energy Axis",
        metro="College Station",
        city="Navasota",
        county="Grimes County",
        region="Central Texas",
        university_anchor="Texas A&M University",
        acreage_band="260-390 acres",
        distance_to_city_miles=24,
        distance_to_university_miles=24,
        viability_score=87,
        power_score=89,
        fiber_score=79,
        water_score=83,
        talent_score=84,
        readiness_stage="Near-term build",
        power_profile="large-format utility room",
        fiber_profile="regional fiber growth options",
        water_profile="reservoir-supported planning potential",
        lat=30.3900,
        lon=-96.0900,
    ),
    OpportunitySeed(
        site_name="Huntsville Fiber Recovery Yard",
        corridor_name="College Station Research Energy Axis",
        metro="East Texas Connector",
        city="Huntsville",
        county="Walker County",
        region="East Texas",
        university_anchor="Sam Houston State University",
        acreage_band="200-310 acres",
        distance_to_city_miles=18,
        distance_to_university_miles=2,
        viability_score=84,
        power_score=84,
        fiber_score=82,
        water_score=81,
        talent_score=85,
        readiness_stage="Strategic reserve",
        power_profile="steady utility expansion potential",
        fiber_profile="north Houston backhaul reach",
        water_profile="regional municipal planning",
        lat=30.7200,
        lon=-95.5500,
    ),
    OpportunitySeed(
        site_name="Waco Riverbend Capacity Belt",
        corridor_name="Central Texas Knowledge Spine",
        metro="Waco",
        city="Waco",
        county="McLennan County",
        region="Central Texas",
        university_anchor="Baylor University",
        acreage_band="150-230 acres",
        distance_to_city_miles=11,
        distance_to_university_miles=5,
        viability_score=90,
        power_score=88,
        fiber_score=85,
        water_score=84,
        talent_score=91,
        readiness_stage="Priority now",
        power_profile="balanced utility redundancy",
        fiber_profile="I-35 mid-state network reach",
        water_profile="reliable municipal and river-adjacent planning",
        lat=31.5500,
        lon=-97.1500,
    ),
    OpportunitySeed(
        site_name="Temple Medical Compute Shelf",
        corridor_name="Central Texas Knowledge Spine",
        metro="Temple-Killeen",
        city="Temple",
        county="Bell County",
        region="Central Texas",
        university_anchor="University of Mary Hardin-Baylor",
        acreage_band="160-240 acres",
        distance_to_city_miles=12,
        distance_to_university_miles=13,
        viability_score=87,
        power_score=86,
        fiber_score=83,
        water_score=84,
        talent_score=86,
        readiness_stage="Near-term build",
        power_profile="steady central Texas utility supply",
        fiber_profile="medical and interstate network adjacency",
        water_profile="predictable municipal service envelope",
        lat=31.1000,
        lon=-97.3400,
    ),
    OpportunitySeed(
        site_name="Belton Growth Relay",
        corridor_name="Central Texas Knowledge Spine",
        metro="Temple-Killeen",
        city="Belton",
        county="Bell County",
        region="Central Texas",
        university_anchor="University of Mary Hardin-Baylor",
        acreage_band="190-280 acres",
        distance_to_city_miles=9,
        distance_to_university_miles=3,
        viability_score=86,
        power_score=85,
        fiber_score=82,
        water_score=84,
        talent_score=87,
        readiness_stage="Near-term build",
        power_profile="growth-oriented utility planning",
        fiber_profile="corridor network continuity",
        water_profile="durable municipal water access",
        lat=31.0500,
        lon=-97.4600,
    ),
    OpportunitySeed(
        site_name="Hillsboro Interstate Reserve",
        corridor_name="Central Texas Knowledge Spine",
        metro="Waco-Dallas Connector",
        city="Hillsboro",
        county="Hill County",
        region="Central Texas",
        university_anchor="Baylor University",
        acreage_band="260-380 acres",
        distance_to_city_miles=28,
        distance_to_university_miles=30,
        viability_score=82,
        power_score=84,
        fiber_score=78,
        water_score=80,
        talent_score=80,
        readiness_stage="Strategic reserve",
        power_profile="roomy utility expansion corridor",
        fiber_profile="interstate backhaul potential",
        water_profile="long-horizon municipal planning",
        lat=32.0100,
        lon=-97.1300,
    ),
    OpportunitySeed(
        site_name="El Paso Northeast Switchyard",
        corridor_name="El Paso Border Gateway",
        metro="El Paso",
        city="El Paso",
        county="El Paso County",
        region="West Texas",
        university_anchor="University of Texas at El Paso",
        acreage_band="180-260 acres",
        distance_to_city_miles=14,
        distance_to_university_miles=11,
        viability_score=91,
        power_score=90,
        fiber_score=84,
        water_score=78,
        talent_score=89,
        readiness_stage="Priority now",
        power_profile="border utility interconnect strength",
        fiber_profile="cross-border carrier reach",
        water_profile="carefully managed municipal supply",
        lat=31.8500,
        lon=-106.3600,
    ),
    OpportunitySeed(
        site_name="Socorro Manufacturing Grid",
        corridor_name="El Paso Border Gateway",
        metro="El Paso",
        city="Socorro",
        county="El Paso County",
        region="West Texas",
        university_anchor="University of Texas at El Paso",
        acreage_band="170-250 acres",
        distance_to_city_miles=18,
        distance_to_university_miles=16,
        viability_score=89,
        power_score=88,
        fiber_score=83,
        water_score=79,
        talent_score=87,
        readiness_stage="Priority now",
        power_profile="industrial utility preparedness",
        fiber_profile="border logistics network access",
        water_profile="municipal supply with industrial planning",
        lat=31.6500,
        lon=-106.2700,
    ),
    OpportunitySeed(
        site_name="Horizon City Expansion Terrace",
        corridor_name="El Paso Border Gateway",
        metro="El Paso",
        city="Horizon City",
        county="El Paso County",
        region="West Texas",
        university_anchor="University of Texas at El Paso",
        acreage_band="220-330 acres",
        distance_to_city_miles=24,
        distance_to_university_miles=22,
        viability_score=87,
        power_score=87,
        fiber_score=80,
        water_score=79,
        talent_score=84,
        readiness_stage="Near-term build",
        power_profile="growing utility footprint",
        fiber_profile="east El Paso backhaul extensions",
        water_profile="planned supply growth",
        lat=31.6900,
        lon=-106.2100,
    ),
    OpportunitySeed(
        site_name="Canutillo Desert Capacity Belt",
        corridor_name="El Paso Border Gateway",
        metro="El Paso",
        city="Canutillo",
        county="El Paso County",
        region="West Texas",
        university_anchor="University of Texas at El Paso",
        acreage_band="200-320 acres",
        distance_to_city_miles=18,
        distance_to_university_miles=16,
        viability_score=84,
        power_score=85,
        fiber_score=79,
        water_score=76,
        talent_score=82,
        readiness_stage="Strategic reserve",
        power_profile="large-site utility flexibility",
        fiber_profile="cross-state corridor access",
        water_profile="conservative long-range water planning",
        lat=31.9200,
        lon=-106.6000,
    ),
    OpportunitySeed(
        site_name="Lubbock North Research Loop",
        corridor_name="Lubbock High Plains Compute Belt",
        metro="Lubbock",
        city="Lubbock",
        county="Lubbock County",
        region="West Texas",
        university_anchor="Texas Tech University",
        acreage_band="180-260 acres",
        distance_to_city_miles=9,
        distance_to_university_miles=5,
        viability_score=90,
        power_score=88,
        fiber_score=82,
        water_score=80,
        talent_score=92,
        readiness_stage="Priority now",
        power_profile="high plains utility reliability",
        fiber_profile="research corridor network reach",
        water_profile="municipal planning with reuse pathways",
        lat=33.6500,
        lon=-101.9000,
    ),
    OpportunitySeed(
        site_name="Wolfforth Utility Reserve",
        corridor_name="Lubbock High Plains Compute Belt",
        metro="Lubbock",
        city="Wolfforth",
        county="Lubbock County",
        region="West Texas",
        university_anchor="Texas Tech University",
        acreage_band="210-300 acres",
        distance_to_city_miles=12,
        distance_to_university_miles=10,
        viability_score=88,
        power_score=89,
        fiber_score=80,
        water_score=79,
        talent_score=88,
        readiness_stage="Near-term build",
        power_profile="scalable utility frontage",
        fiber_profile="regional backhaul continuity",
        water_profile="municipal growth flexibility",
        lat=33.5000,
        lon=-102.0000,
    ),
    OpportunitySeed(
        site_name="Plainview Ag-Tech Capacity Shelf",
        corridor_name="Lubbock High Plains Compute Belt",
        metro="Lubbock-Plainview",
        city="Plainview",
        county="Hale County",
        region="West Texas",
        university_anchor="Texas Tech University",
        acreage_band="260-390 acres",
        distance_to_city_miles=38,
        distance_to_university_miles=42,
        viability_score=82,
        power_score=84,
        fiber_score=75,
        water_score=77,
        talent_score=80,
        readiness_stage="Strategic reserve",
        power_profile="large-format utility optionality",
        fiber_profile="regional transport network potential",
        water_profile="careful agricultural-region water planning",
        lat=34.1800,
        lon=-101.7100,
    ),
    OpportunitySeed(
        site_name="Levelland West Texas Relay",
        corridor_name="Lubbock High Plains Compute Belt",
        metro="Lubbock-Levelland",
        city="Levelland",
        county="Hockley County",
        region="West Texas",
        university_anchor="Texas Tech University",
        acreage_band="240-360 acres",
        distance_to_city_miles=35,
        distance_to_university_miles=34,
        viability_score=81,
        power_score=83,
        fiber_score=74,
        water_score=78,
        talent_score=79,
        readiness_stage="Strategic reserve",
        power_profile="westward utility expansion room",
        fiber_profile="regional network build potential",
        water_profile="prudent municipal planning",
        lat=33.5900,
        lon=-102.3700,
    ),
    OpportunitySeed(
        site_name="Midland Energy Backbone Campus",
        corridor_name="Permian Basin Energy Transition Belt",
        metro="Midland-Odessa",
        city="Midland",
        county="Midland County",
        region="Permian Basin",
        university_anchor="University of Texas Permian Basin",
        acreage_band="200-290 acres",
        distance_to_city_miles=11,
        distance_to_university_miles=17,
        viability_score=89,
        power_score=92,
        fiber_score=78,
        water_score=76,
        talent_score=84,
        readiness_stage="Priority now",
        power_profile="energy-market utility depth",
        fiber_profile="oilfield corridor backhaul reach",
        water_profile="industrial water reuse planning",
        lat=31.9900,
        lon=-102.0800,
    ),
    OpportunitySeed(
        site_name="Odessa Substation Growth Ridge",
        corridor_name="Permian Basin Energy Transition Belt",
        metro="Midland-Odessa",
        city="Odessa",
        county="Ector County",
        region="Permian Basin",
        university_anchor="University of Texas Permian Basin",
        acreage_band="220-320 acres",
        distance_to_city_miles=14,
        distance_to_university_miles=21,
        viability_score=86,
        power_score=90,
        fiber_score=76,
        water_score=75,
        talent_score=81,
        readiness_stage="Near-term build",
        power_profile="substation-adjacent expansion room",
        fiber_profile="energy corridor network access",
        water_profile="industrial supply planning",
        lat=31.8500,
        lon=-102.3700,
    ),
    OpportunitySeed(
        site_name="Greenwood Reserve Power Shelf",
        corridor_name="Permian Basin Energy Transition Belt",
        metro="Midland-Odessa",
        city="Greenwood",
        county="Midland County",
        region="Permian Basin",
        university_anchor="University of Texas Permian Basin",
        acreage_band="280-420 acres",
        distance_to_city_miles=19,
        distance_to_university_miles=24,
        viability_score=83,
        power_score=88,
        fiber_score=72,
        water_score=74,
        talent_score=79,
        readiness_stage="Strategic reserve",
        power_profile="oversized utility staging potential",
        fiber_profile="regional transport expansion paths",
        water_profile="long-range industrial reuse planning",
        lat=32.0200,
        lon=-102.1900,
    ),
    OpportunitySeed(
        site_name="Corpus Christi Port Fiber Yard",
        corridor_name="Coastal Logistics Capacity Belt",
        metro="Corpus Christi",
        city="Corpus Christi",
        county="Nueces County",
        region="Gulf Coast",
        university_anchor="Texas A&M University-Corpus Christi",
        acreage_band="150-230 acres",
        distance_to_city_miles=9,
        distance_to_university_miles=7,
        viability_score=88,
        power_score=85,
        fiber_score=84,
        water_score=82,
        talent_score=85,
        readiness_stage="Priority now",
        power_profile="port-adjacent utility resilience",
        fiber_profile="coastal carrier adjacency",
        water_profile="municipal and industrial reuse options",
        lat=27.8000,
        lon=-97.4000,
    ),
    OpportunitySeed(
        site_name="Portland Bayfront Utility Shelf",
        corridor_name="Coastal Logistics Capacity Belt",
        metro="Corpus Christi",
        city="Portland",
        county="San Patricio County",
        region="Gulf Coast",
        university_anchor="Texas A&M University-Corpus Christi",
        acreage_band="190-280 acres",
        distance_to_city_miles=15,
        distance_to_university_miles=18,
        viability_score=85,
        power_score=84,
        fiber_score=81,
        water_score=83,
        talent_score=81,
        readiness_stage="Near-term build",
        power_profile="gulf utility access",
        fiber_profile="coastal backhaul continuity",
        water_profile="strong municipal-industrial planning",
        lat=27.8800,
        lon=-97.3200,
    ),
    OpportunitySeed(
        site_name="Kingsville Inland Expansion Zone",
        corridor_name="Coastal Logistics Capacity Belt",
        metro="Corpus Christi-Kingsville",
        city="Kingsville",
        county="Kleberg County",
        region="South Texas",
        university_anchor="Texas A&M University-Kingsville",
        acreage_band="220-340 acres",
        distance_to_city_miles=14,
        distance_to_university_miles=3,
        viability_score=84,
        power_score=83,
        fiber_score=78,
        water_score=82,
        talent_score=82,
        readiness_stage="Near-term build",
        power_profile="large-block utility growth potential",
        fiber_profile="south coastal network access",
        water_profile="stable municipal planning",
        lat=27.5200,
        lon=-97.8600,
    ),
    OpportunitySeed(
        site_name="Edinburg Research Access Yard",
        corridor_name="Rio Grande Valley Cross-Border Belt",
        metro="Rio Grande Valley",
        city="Edinburg",
        county="Hidalgo County",
        region="South Texas",
        university_anchor="University of Texas Rio Grande Valley",
        acreage_band="150-230 acres",
        distance_to_city_miles=6,
        distance_to_university_miles=3,
        viability_score=88,
        power_score=84,
        fiber_score=82,
        water_score=78,
        talent_score=89,
        readiness_stage="Priority now",
        power_profile="steady regional utility service",
        fiber_profile="cross-border carrier access",
        water_profile="careful municipal water stewardship",
        lat=26.3000,
        lon=-98.1700,
    ),
    OpportunitySeed(
        site_name="McAllen Logistics Grid Node",
        corridor_name="Rio Grande Valley Cross-Border Belt",
        metro="Rio Grande Valley",
        city="McAllen",
        county="Hidalgo County",
        region="South Texas",
        university_anchor="University of Texas Rio Grande Valley",
        acreage_band="170-260 acres",
        distance_to_city_miles=7,
        distance_to_university_miles=9,
        viability_score=87,
        power_score=83,
        fiber_score=83,
        water_score=77,
        talent_score=87,
        readiness_stage="Priority now",
        power_profile="cross-border utility continuity",
        fiber_profile="border logistics network density",
        water_profile="municipal service with reuse planning",
        lat=26.2000,
        lon=-98.2300,
    ),
    OpportunitySeed(
        site_name="Brownsville Port Talent Interface",
        corridor_name="Rio Grande Valley Cross-Border Belt",
        metro="Rio Grande Valley",
        city="Brownsville",
        county="Cameron County",
        region="South Texas",
        university_anchor="University of Texas Rio Grande Valley",
        acreage_band="190-290 acres",
        distance_to_city_miles=9,
        distance_to_university_miles=24,
        viability_score=85,
        power_score=82,
        fiber_score=80,
        water_score=78,
        talent_score=84,
        readiness_stage="Near-term build",
        power_profile="port-connected utility access",
        fiber_profile="southmost logistics backhaul",
        water_profile="municipal planning near industrial users",
        lat=25.9000,
        lon=-97.5000,
    ),
    OpportunitySeed(
        site_name="Harlingen South Texas Reserve",
        corridor_name="Rio Grande Valley Cross-Border Belt",
        metro="Rio Grande Valley",
        city="Harlingen",
        county="Cameron County",
        region="South Texas",
        university_anchor="University of Texas Rio Grande Valley",
        acreage_band="220-320 acres",
        distance_to_city_miles=12,
        distance_to_university_miles=18,
        viability_score=84,
        power_score=82,
        fiber_score=78,
        water_score=79,
        talent_score=83,
        readiness_stage="Near-term build",
        power_profile="roomy south Texas utility envelope",
        fiber_profile="valley transport network access",
        water_profile="regional municipal planning",
        lat=26.1900,
        lon=-97.7000,
    ),
)


def build_customer_dashboard_summary(
    settings: Settings,
    *,
    db_session: Session | None,
    monitoring_snapshot: dict[str, Any],
    source_inventory_snapshot: dict[str, Any],
) -> dict[str, Any]:
    live_opportunities: list[dict[str, Any]] = []
    if db_session is not None:
        try:
            live_opportunities = build_live_candidate_opportunities(db_session)
        except Exception:
            live_opportunities = []

    snapshot_opportunities = [] if live_opportunities else _load_client_contender_snapshot(settings)
    if live_opportunities:
        data_mode = "live_candidate_scoring"
        opportunities = live_opportunities
    elif snapshot_opportunities:
        data_mode = "client_snapshot"
        opportunities = snapshot_opportunities
    else:
        data_mode = "seeded_catalog"
        opportunities = _build_opportunities()
    market_backed_mode = data_mode in {"live_candidate_scoring", "client_snapshot"}
    featured_opportunities = opportunities[:6]
    corridors = _build_corridors(opportunities)
    unique_universities = sorted(
        {item["university_anchor"] for item in opportunities},
    )
    generated_at = datetime.now(UTC).isoformat()
    priority_now_count = sum(
        1 for item in opportunities if item["readiness_stage"] == "Priority now"
    )
    top_tier_count = sum(1 for item in opportunities if item["score_band"] == "Tier 1")
    opportunity_count = len(opportunities)

    return {
        "app_name": settings.app_name,
        "display_name": "Texas Private Client Siting Portal",
        "environment": settings.app_env,
        "version": "0.1.0",
        "generated_at": generated_at,
        "market": "Texas",
        "data_mode": data_mode,
        "hero_title": (
            f"{opportunity_count} live-ranked Texas opportunities balanced across major metros."
            if market_backed_mode
            else (
                f"{opportunity_count} ranked Texas opportunities near cities, utilities, "
                "and university talent."
            )
        ),
        "hero_subtitle": (
            "Candidate-first grading is using live marketed sites plus public infrastructure "
            "signals, with a social-political approval overlay and minimum major-metro coverage "
            "for client review."
            if market_backed_mode
            else (
                "Private shortlist designed to help client principals and site selectors focus on "
                "metros and corridors where power, fiber, land scale, workforce depth, and "
                "approval friction align."
            )
        ),
        "opportunity_count": opportunity_count,
        "priority_now_count": priority_now_count,
        "top_tier_count": top_tier_count,
        "corridor_count": len(corridors),
        "university_count": len(unique_universities),
        "metrics": _build_metrics(
            opportunities,
            priority_now_count=priority_now_count,
            corridor_count=len(corridors),
            university_count=len(unique_universities),
            source_inventory_snapshot=source_inventory_snapshot,
            data_mode=data_mode,
        ),
        "filters": _build_filters(opportunities, unique_universities=unique_universities),
        "featured_opportunities": featured_opportunities,
        "opportunities": opportunities,
        "corridors": corridors,
        "data_coverage": source_inventory_snapshot,
        "monitoring": monitoring_snapshot,
    }


def _load_client_contender_snapshot(settings: Settings) -> list[dict[str, Any]]:
    path = Path(settings.client_contender_snapshot_path)
    if not path.is_absolute():
        path = Path.cwd() / path

    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return []

    opportunities = payload.get("opportunities")
    if not isinstance(opportunities, list):
        return []

    return [dict(item) for item in opportunities if isinstance(item, dict)]


def _build_opportunities() -> list[dict[str, Any]]:
    ranked = sorted(
        _OPPORTUNITY_SEEDS,
        key=lambda item: (
            -item.viability_score,
            -item.power_score,
            -item.fiber_score,
            item.site_name,
        ),
    )

    opportunities: list[dict[str, Any]] = []
    for rank, seed in enumerate(ranked, start=1):
        approval_overlay = build_social_political_overlay(
            metro_name=seed.metro,
            region=seed.region,
            city_distance=float(seed.distance_to_city_miles),
            university_distance=float(seed.distance_to_university_miles),
            acreage=_seed_acreage_estimate(seed.acreage_band),
            building_sqft=None,
            water_score=seed.water_score,
            environment_score=max(seed.water_score - 4, 52),
            hazard_score=max(seed.water_score - 6, 50),
        )
        acreage_estimate = _seed_acreage_estimate(seed.acreage_band)
        opportunities.append(
            {
                "rank": rank,
                "site_id": _site_id(seed, rank),
                "site_name": seed.site_name,
                "corridor_name": seed.corridor_name,
                "metro": seed.metro,
                "city": seed.city,
                "county": seed.county,
                "region": seed.region,
                "university_anchor": seed.university_anchor,
                "acreage": acreage_estimate,
                "acreage_band": seed.acreage_band,
                "distance_to_city_miles": seed.distance_to_city_miles,
                "distance_to_university_miles": seed.distance_to_university_miles,
                "viability_score": seed.viability_score,
                "power_score": seed.power_score,
                "fiber_score": seed.fiber_score,
                "water_score": seed.water_score,
                "talent_score": seed.talent_score,
                "readiness_stage": seed.readiness_stage,
                "score_band": _score_band(seed.viability_score),
                "strengths": [
                    seed.power_profile,
                    seed.fiber_profile,
                    seed.water_profile,
                ],
                "summary": (
                    f"Strong on {seed.power_profile}, {seed.fiber_profile}, and "
                    f"{seed.water_profile} with access to {seed.university_anchor} talent."
                ),
                "lat": seed.lat,
                "lon": seed.lon,
                **approval_overlay,
            }
        )
    return opportunities


def _build_corridors(opportunities: list[dict[str, Any]]) -> list[dict[str, Any]]:
    grouped: dict[str, list[dict[str, Any]]] = {}
    for item in opportunities:
        grouped.setdefault(item["corridor_name"], []).append(item)

    corridors: list[dict[str, Any]] = []
    for corridor_name, items in grouped.items():
        corridors.append(
            {
                "name": corridor_name,
                "site_count": len(items),
                "average_viability_score": round(
                    mean(item["viability_score"] for item in items),
                    1,
                ),
                "priority_now_count": sum(
                    1 for item in items if item["readiness_stage"] == "Priority now"
                ),
                "lead_metro": items[0]["metro"],
                "lead_university": items[0]["university_anchor"],
            }
        )

    return sorted(
        corridors,
        key=lambda item: (-item["average_viability_score"], -item["site_count"], item["name"]),
    )


def _build_metrics(
    opportunities: list[dict[str, Any]],
    *,
    priority_now_count: int,
    corridor_count: int,
    university_count: int,
    source_inventory_snapshot: dict[str, Any],
    data_mode: str,
) -> list[dict[str, Any]]:
    planned_sources = int(source_inventory_snapshot.get("total_sources") or 0)
    market_backed_mode = data_mode in {"live_candidate_scoring", "client_snapshot"}
    return [
        {
            "label": "Texas opportunities",
            "value": len(opportunities),
            "detail": (
                "Live-scored marketed candidates ranked for private client review across Texas."
                if market_backed_mode
                else "Ranked candidate sites seeded for private client review across the state."
            ),
            "tone": "teal",
        },
        {
            "label": "Priority-now sites",
            "value": priority_now_count,
            "detail": (
                "Highest-confidence live candidates ready for immediate parcel validation."
                if market_backed_mode
                else "Highest-confidence corridors ready for immediate parcel sourcing."
            ),
            "tone": "gold",
        },
        {
            "label": "Metro corridors",
            "value": corridor_count,
            "detail": "Coverage across North Texas, Central Texas, the Gulf Coast, and West Texas.",
            "tone": "navy",
        },
        {
            "label": "University anchors",
            "value": university_count,
            "detail": "Research and workforce magnets tied to the current watchlist.",
            "tone": "rust",
        },
        {
            "label": "Public data sources",
            "value": planned_sources,
            "detail": (
                "Authoritative free sources planned to back the live parcel-scoring pipeline."
            ),
            "tone": "sage",
        },
    ]


def _build_filters(
    opportunities: list[dict[str, Any]],
    *,
    unique_universities: list[str],
) -> dict[str, list[str]]:
    return {
        "metros": sorted({item["metro"] for item in opportunities}),
        "readiness_stages": sorted({item["readiness_stage"] for item in opportunities}),
        "corridors": sorted({item["corridor_name"] for item in opportunities}),
        "university_anchors": unique_universities,
    }


def _seed_acreage_estimate(acreage_band: str) -> float | None:
    matches = re.findall(r"\d+(?:\.\d+)?", acreage_band)
    if not matches:
        return None
    values = [float(item) for item in matches[:2]]
    if len(values) == 1:
        return values[0]
    return round(mean(values), 1)


def _score_band(score: int) -> str:
    if score >= 92:
        return "Tier 1"
    if score >= 86:
        return "Tier 2"
    return "Tier 3"


def _site_id(seed: OpportunitySeed, rank: int) -> str:
    return f"tx-{_slugify(seed.corridor_name)}-{_slugify(seed.city)}-{rank:02d}"


def _slugify(value: str) -> str:
    return "-".join(
        chunk
        for chunk in "".join(
            character.lower() if character.isalnum() else " "
            for character in value
        ).split()
        if chunk
    )
